### ISSUE TITLE
开启该插件后，易通行在欢迎页闪退

### ISSUE THREAD

**Issue by githubnimabi** [ohyeah521/RuubyPayAdAway#1]
作者你好，我手机是一加6 android8.1(H2OS 5.1.14)，易通行版本是2.6.2，在xp中激活该插件之后，点开该插件，会提示是最新版本，并且 易通行 去广告已经开启，这时候我点击 易通行，在欢迎页面就闪退了，不能进入易通行app，望作者知悉，有时间的话，帮忙查找一下问题原因，万分感谢！另外，还有一个额外的诉求，如果该插件能实现去除易通行的更新弹框、当点开易通行后，app默认展示二维码页面，就最好了，，哈哈，加油~~

**Comment by githubnimabi** [comment]
最新版3.0.2的易通行也会闪退

**Comment by ohyeah521** [comment]
@githubnimabi 

1、崩溃问题：可能是您的易通行版本太低了，请升级到最新版本（v3.0.1）。因为该软件使用了商业包含软件进行加固，被加固后的app的路径可能不同，或者是软件开发者改写了某些功能，导致不兼容。
2、启动后默认显示二维码：这个功能我得在逆向一下源软件，然后在下一个版本中加入这个功能。
3、去除更新对话框是什么意思？禁止更新？还是只要不提示更新对话框就可以了？

**Comment by ohyeah521** [comment]
> 最新版3.0.2的易通行也会闪退

最新版本是3.0.1吧，在哪里下载的3.0.2？

**Comment by githubnimabi** [comment]
1.去除更新对话框：有时候更新的对话框会覆盖在二维码的页面上，还得手动点击暂不更新才能展示出二维码，个人感觉很麻烦，我觉得只要不显示对话框就好了，用户可以自己手动去检查更新或者在手机的应用商店进行更新

**Comment by githubnimabi** [comment]
我之前是2.6.2版本，易通行app内一直提示更新，我直接在app内更新下载的，安装之后就是3.0.2版本

**Comment by ohyeah521** [comment]
> 1.去除更新对话框：有时候更新的对话框会覆盖在二维码的页面上，还得手动点击暂不更新才能展示出二维码，个人感觉很麻烦，我觉得只要不显示对话框就好了，用户可以自己手动去检查更新或者在手机的应用商店进行更新

我了解需求了，会在下一个版本更新

**Comment by githubnimabi** [comment]
> > 1.去除更新对话框：有时候更新的对话框会覆盖在二维码的页面上，还得手动点击暂不更新才能展示出二维码，个人感觉很麻烦，我觉得只要不显示对话框就好了，用户可以自己手动去检查更新或者在手机的应用商店进行更新
> 
> 我了解需求了，会在下一个版本更新

好的，多谢多谢~

**Comment by ohyeah521** [comment]
> 我之前是2.6.2版本，易通行app内一直提示更新，我直接在app内更新下载的，安装之后就是3.0.2版本

了解了，我去找个3.0.2试试

**Comment by githubnimabi** [comment]
> > 我之前是2.6.2版本，易通行app内一直提示更新，我直接在app内更新下载的，安装之后就是3.0.2版本
> 
> 了解了，我去找个3.0.2试试

辛苦辛苦~

**Comment by ohyeah521** [comment]
@githubnimabi 

崩溃问题貌似不是插件导致的，我找了三台机器，关闭插件后，有一台机器的《易通行》 v3.0.2版本还是会崩溃，通过逆向分析来看，这是官方放出的一个debug应用，部分机型会出现崩溃情况。你可以关闭插件试试，应该还是会崩溃的，如果还崩溃，你可以试试v3.0.1版本

**Comment by githubnimabi** [comment]
> @githubnimabi
> 
> 崩溃问题貌似不是插件导致的，我找了三台机器，关闭插件后，有一台机器的《易通行》 v3.0.2版本还是会崩溃，通过逆向分析来看，这是官方放出的一个debug应用，部分机型会出现崩溃情况。你可以关闭插件试试，应该还是会崩溃的，如果还崩溃，你可以试试v3.0.1版本

我下午试过了，开了插件，302的版本就甭，在xp里取消打勾，重启手机，再点易通行，他就不蹦了，，我现在301版本的试试，多谢

**Comment by ohyeah521** [comment]
@githubnimabi  你家一下我微信，我发你一个测试版试试。 微信： hibandit
