### ISSUE TITLE
请适配太极Xposed

### ISSUE THREAD

**Issue by FSPaul2498** [ohyeah521/RuubyPayAdAway#2]
作者您好，希望您能够适配太极Xposed，让一众9.0机型也可以使用您的模块，谢谢~

注：【太极】Xposed是由维术开发的、可以在全机型上工作的Xposed解决方案，【太极·阴】支持在任何机型上，免解锁免Root实现大部分Xposed功能（需要重签名APK），而【太极·阳】支持通过Magisk模块，在任何机型上实现完整的Xposed功能。

鉴于目前众多Android手机已经升级到了Android 9.0，而9.0及以上系统尚无法使用原版Xposed，这可能是目前Android 9.0以上，最好的Xposed解决方案了。唯一的缺点是，太极Xposed需要模块开发者主动进行兼容，才能在太极上工作，所以希望作者能够和太极合作，尽快实现模块在太极上工作，谢谢！

太极官网：【[https://taichi.cool](url)】或【[https://m.taichi.cool](url)】

**Comment by ohyeah521** [comment]
好的，我会利用周末的时间对太极Xposed进行试配

**Comment by FSPaul2498** [comment]
好的，感谢开发者的及时回复与跟进~

**Comment by ohyeah521** [comment]
太极非常的恶意，发布插件，他们要审核，而且速度极慢，已经多次反馈无果。
