### ISSUE TITLE
建议添加【隐藏桌面应用图标】功能

### ISSUE THREAD

**Issue by FSPaul2498** [ohyeah521/RuubyPayAdAway#3]
如题，因为从功能角度来讲，这个模块的开启频率真的很低，所以能否提供一个【隐藏桌面应用图标】的功能，节省一个桌面图标位。（默认不隐藏，可手动启用）需要打开时也可以从Xposed设置中打开，并不会影响使用

**Comment by ohyeah521** [comment]
此功能非刚需，隐藏后一些小白可能就找不到了

**Comment by FSPaul2498** [comment]
这个功能确实不是刚需，不过这样也确实可以让手机的桌面更简洁一些，毕竟这个模块的打开频率真的很低。不妨设计成默认显示，可以在设置中开启隐藏模式（配图为核心破解模块，以供参考）
![Screenshot_2019-05-24-21-52-32-460_me weishu core](https://user-images.githubusercontent.com/35190475/58332779-8a1a6a00-7e6e-11e9-8fc8-3374c8958318.png)

**Comment by ohyeah521** [comment]
@FSPaul2498  请卸载就版本，安装2.x版本，已经支持隐藏图标了。
